/// Flutter icons Arbenn
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Arbenn
///      fonts:
///       - asset: fonts/Arbenn.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class ArbennIcons {
  ArbennIcons._();

  static const fontName = 'ArbennIcons';

  static const IconData sliders = IconData(0xe900, fontFamily: fontName);
  static const IconData bell = IconData(0xe902, fontFamily: fontName);
  static const IconData calendar = IconData(0xe903, fontFamily: fontName);
  static const IconData plainChevronDown =
      IconData(0xe904, fontFamily: fontName);
  static const IconData plainChevronLeft =
      IconData(0xe905, fontFamily: fontName);
  static const IconData plainChevronRight =
      IconData(0xe906, fontFamily: fontName);
  static const IconData plainChevronUp = IconData(0xe907, fontFamily: fontName);
  static const IconData chevronDown = IconData(0xe908, fontFamily: fontName);
  static const IconData chevronLeft = IconData(0xe909, fontFamily: fontName);
  static const IconData chevronRight = IconData(0xe90a, fontFamily: fontName);
  static const IconData chevronUp = IconData(0xe90b, fontFamily: fontName);
  static const IconData exclamation = IconData(0xe90c, fontFamily: fontName);
  static const IconData info = IconData(0xe90d, fontFamily: fontName);
  static const IconData plus = IconData(0xe90e, fontFamily: fontName);
  static const IconData xmark = IconData(0xe90f, fontFamily: fontName);
  static const IconData clock = IconData(0xe910, fontFamily: fontName);
  static const IconData vdots = IconData(0xe911, fontFamily: fontName);
  static const IconData hdots = IconData(0xe912, fontFamily: fontName);
  static const IconData email = IconData(0xe901, fontFamily: fontName);
  static const IconData eyeSlash = IconData(0xe913, fontFamily: fontName);
  static const IconData eye = IconData(0xe914, fontFamily: fontName);
  static const IconData gear = IconData(0xe915, fontFamily: fontName);
  static const IconData hashtag = IconData(0xe916, fontFamily: fontName);
  static const IconData home = IconData(0xe917, fontFamily: fontName);
  static const IconData back = IconData(0xe918, fontFamily: fontName);
  static const IconData location = IconData(0xe919, fontFamily: fontName);
  static const IconData search = IconData(0xe91a, fontFamily: fontName);
  static const IconData pencil = IconData(0xe91b, fontFamily: fontName);
  static const IconData userGroup = IconData(0xe91c, fontFamily: fontName);
  static const IconData user = IconData(0xe91d, fontFamily: fontName);
  static const IconData addPhoto = IconData(0xe91e, fontFamily: fontName);
}
