/// Flutter icons Arbenn
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Arbenn
///      fonts:
///       - asset: fonts/Arbenn.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class ArbennIcons {
  ArbennIcons._();

  static const fontName = 'ArbennIcons';

  static const IconData sliders = IconData(0xf1de, fontFamily: fontName);
  static const IconData bell = IconData(0xf0f3, fontFamily: fontName);
  static const IconData calendar = IconData(0xf073, fontFamily: fontName);
  static const IconData plainChevronDown =
      IconData(0xf0d7, fontFamily: fontName);
  static const IconData plainChevronLeft =
      IconData(0xf0d9, fontFamily: fontName);
  static const IconData plainChevronRight =
      IconData(0xf0da, fontFamily: fontName);
  static const IconData plainChevronUp = IconData(0xf0d8, fontFamily: fontName);
  static const IconData chevronDown = IconData(0xf078, fontFamily: fontName);
  static const IconData chevronLeft = IconData(0xf053, fontFamily: fontName);
  static const IconData chevronRight = IconData(0xf054, fontFamily: fontName);
  static const IconData chevronUp = IconData(0xf077, fontFamily: fontName);
  static const IconData exclamation = IconData(0xf06a, fontFamily: fontName);
  static const IconData info = IconData(0xf05a, fontFamily: fontName);
  static const IconData plus = IconData(0xf055, fontFamily: fontName);
  static const IconData xmark = IconData(0xf00d, fontFamily: fontName);
  static const IconData clock = IconData(0xf017, fontFamily: fontName);
  static const IconData vdots = IconData(0xf142, fontFamily: fontName);
  static const IconData hdots = IconData(0xf141, fontFamily: fontName);
  static const IconData email = IconData(0xf0e0, fontFamily: fontName);
  static const IconData eyeSlash = IconData(0xf070, fontFamily: fontName);
  static const IconData eye = IconData(0xf06e, fontFamily: fontName);
  static const IconData gear = IconData(0xf013, fontFamily: fontName);
  static const IconData hashtag = IconData(0x0023, fontFamily: fontName);
  static const IconData home = IconData(0xf015, fontFamily: fontName);
  static const IconData back = IconData(0xf060, fontFamily: fontName);
  static const IconData next = IconData(0xf061, fontFamily: fontName);
  static const IconData location = IconData(0xf3c5, fontFamily: fontName);
  static const IconData search = IconData(0xf002, fontFamily: fontName);
  static const IconData pencil = IconData(0xf304, fontFamily: fontName);
  static const IconData userGroup = IconData(0xf500, fontFamily: fontName);
  static const IconData user = IconData(0xf007, fontFamily: fontName);
  static const IconData addPhoto = IconData(0xf030, fontFamily: fontName);
  static const IconData send = IconData(0xf1d8, fontFamily: fontName);
  static const IconData check = IconData(0xf00c, fontFamily: fontName);
}
